version: "3"

services:
  backend:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    env_file:
      - .env
